Feature/get current user
ScalaInc/exp-android-sdk pull request #35
Opened 2017-01-06 20:20 UTC by cesar-oyarzun-m

2017-04-19 22:54 UTC, adamgallowayscala requested changes

2017-04-19 22:54 UTC, adamgallowayscala commented on exp-android-sdk/src/main/java/com/scala/exp/android/sdk/Runtime.java
> +    public static Observable<Boolean> start_auth(final Auth auth){
use camel case for method names

2017-04-19 22:54 UTC, adamgallowayscala commented on exp-android-sdk/src/main/java/com/scala/exp/android/sdk/model/Auth.java
> +    public Api getApi() {return api;}
formate on new line, like other methods

2017-04-19 22:54 UTC, adamgallowayscala commented on exp-android-sdk/src/main/java/com/scala/exp/android/sdk/model/Auth.java
> +    public void setApi(Api api) {this.api = api;}
format on new line

2017-04-19 22:54 UTC, adamgallowayscala commented on exp-android-sdk/src/main/java/com/scala/exp/android/sdk/Runtime.java
> +    public static Observable<Boolean> start_auth(final Auth auth){
Try to combine this into the other start_auth() method, they seem to share a lot of code

2017-04-20 15:52 UTC, cesar-oyarzun-m commented
@adamgallowayscala PR fixed!

2017-04-27 01:13 UTC, adamgallowayscala approved these changes

2017-04-27 01:13 UTC, merged